var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                             o                  ",
   "   xxxxxx                                                    y                  ",
   "   xxx                                                                          ",
   " @ xxx      yyy                  o                        y                     ",
   "xxx                                                                     o       ",
   "xxx                yyy           o                                              ",
   "xxx                                                                     y       ",
   "xxx                                                     y                       ",
   "xxx                             yyyy                                            ",
   "xxx                                                                             ",
   "xxx                                  o o              yyyyyy                 x  ",
   "xxx                    o              y                          o o      yyyx  ",
   "xxx                                      yyyy    o o            yyyy         xxx",
   "xxx          xxxx   *  o  *                       y                          xxx",
   "xxx  o       xxxx      y     o      yy                                       xxx",
   "xxxxxxxxxxxxxxxxxxx         xxxx          xx         xx            xxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xx         xx            xxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xx       xxxx!!!!!!!!!!!!xxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxx!!!!!!!!!!xx   xxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                  o                                   ",
   "                                                  y   x                               ",
   "                                         y            x                               ",
   "                                              o       x                               ",
   "                                      y       y       x                               ",
   "                                                   o  x                               ",
   "                               o            o      y  x                               ",
   "                                x           y         x                               ",
   "                                x               o     x                               ",
   "                o         o     x o             y    xx                               ",
   "     @          y   o *   x     x         o           x                               ",
   "    xxx             y           x         y           x        o                      ",
   "    x x           *   *         x  o                  x        x                      ",
   "!!!!x x!!!!!!x  *       x!!!!!!xx               y     x!!!!!!!!!!                     ",
   "!!!!x x!!!!!!x          x!!!!!xx                      x!!!!!!!xx!                     ",
   "!!!!x x!!!!!!x          x!!!!!x    o       y          x!!!!!!xx !                     ",
   "!!!!x x!!!!!!x!!!!!!!!!!x!!!!!x                       !!!!!!xx  !                     ",
   "!!!!x x!!!!!!x!!!!!!!!!!x!!!!!xx       xx         !!!!!!!!!xx   !                     ",
   "!!!!x x!!!!!!x!!!!!!!!!!x!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!xx    !                     ",
   "!!!!x x!!!!!!x!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx    !                     "],
  ["                                           !                                          ",
   "                                           !                                          ",
   "                                           !                                          ",
   "                                           !                                          ",
   "                                           !                                          ",
   "                                        o  !                                          ",
   "                                           !                                          ",
   "                                        x  !                                          ",
   "                                        x  !                                          ",
   "                                        x  !                                          ",
   "                                        x  !                                          ",
   "                                       xxx !                                          ",
   "                                       xyx !                o                         ",
   "                                       xyx !                           x              ",
   "                                     xxxyxxx                x          x              ",
   "                               y      xyyyx                 x   oooo   x              ",
   "                                      xyyyx                 x          x              ",
   "                                      xyyyx           xxxxxxxxxxxxxxxxxx              ",
   "                                      xyyyxx      x   x!!!!!!!!!!!!!!!!x              ",
   "                                     xxyyyxx     xx   x!!!!!!!!!!!!!!!!x              ",
   "                                      xyyyx           x!!!!!!!!!!!!!!!!x       o      ",
   "                                      xyyyx           x!!!!!!!!!!!!!!!!x              ",
   "                                      xyyyxx          x!!!!!!!!!!!!!!!!x       y      ",
   "                               y      xyyyx           x!!!!!!!!!!!!!!!!x *          * ",
   "                                      xyyyx     o     x!!!!!!!!!!!!!!!!x              ",
   "                                      xyyyx           x!!!!!!!!!!!!!!!!x              ",
   "                                     xxyyyx     y     x!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!",
   "                              o   o   xyyyx           x!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!",
   "                                      xyyyx          xx!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!",
   "                               x      xxxxx      o o  x!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!",
   "                              xxxxx   xxxxx           x!!!!!!!!!!!!!!!!x *           *",
   "   o                         xx!!!!   !!!!x    xxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "                             xx!!!!   !!!!x                                           ",
   "!!xxx                    o    x!!!!   !!!!x                                o     xxx!!",
   "!!x x                         x!!!!   !!!!x                                      xxx!!",
   "!!x                      y    x!!!!   !!!!xxxxxxx                        xxxxx   xxx!!",
   "!!x         y                 x!!!!   !!!!x                    o         xxxxx * xxx!!",
   "!!x                           x!!!!   !!!!x                              xxxxx   xxx!!",
   "!!x                           x *       * x         yyyy      yyyy     xxxxxxx   xxx!!",
   "!!x                xxx        x                                       xxxxxxxx   xxx!!",
   "!!x               oxxxo       xo         o               o            x!!!!!!!!!!!!!!!",
   "!!x                           x                o                      x!!!!!!!!!!!!!!!",
   "!!x                           xxxxxxxxxxxxxxxx    x!!!!x    x!!!!x    x!!!!!!!!!!!!!!!",
   "!!x      @                    x           x!!x    x!!!!x    x!!!!xoooox!!!!!!!!!!!!!!!",
   "!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
